package-lock.json
package.json
vite.config.ts

- gh-pages 패키지 설치 (npm install --save-dev gh-pages)
- package.json에 predeploy 및 deploy 스크립트 추가
- vite.config.ts 수정하여 base 속성 추가
- GitHub Pages 배포 URL을 homepage 필드에 설정
(https://titovcompany.github.io/Visionlife_FE/)

:sparkle: feat : 배포를 위한 gh-pages 설치 및 설정

---

src/components/Tab/TabNavLinkItem.tsx

> ## PR 타입
> ## 변경 사항
- `TabNavLinkItem` 컴포넌트에서 `NavLink`의 `end` 속성을 추가하여 부모 경로(`/company/profile`)가 자식 경로(`/company/profile/history`, `/company/profile/contact`)에서도 활성화되는 문제를 수정하였습니다.
<br/>
> ## 변경 전 문제
- 기존에는 `/company/profile`이 `/company/profile/history` 또는 `/company/profile/contact`의 부모 경로로 인식되어 "회사 소개" 탭이 계속 활성화되는 문제가 있었습니다.
<br/>
- 현재 경로와 정확히 일치하는 탭만 활성화됨
- 사용자 경험(UX) 개선 및 올바른 내비게이션 동작 보장
<br/>
> ## 테스트 방법
1. `/company/profile` → "회사 소개" 탭 활성화 확인  
2. `/company/profile/history` → "회사 연혁" 탭 활성화 확인
3. `/company/profile/contact` → "오시는 길" 탭 활성화 확인

🐛 Fix : 부모 경로가 자식 경로에서 활성화되는 문제 해결

---

src/features/profile/pages/History.tsx

> ## PR 타입
> ## 변경 사항
중앙에 있던 제목을 왼쪽으로 정렬되게 하였습니다
<br/>
> ## 변경 전 문제
제목 텍스트가 중앙에 위치
<br/>
제목 텍스트가 올바르게 왼쪽에 정렬
<br/>

refactor: HISTORY에있는 중앙의 제목텍스트 왼쪽 정렬되게 수정

---

src/features/business-overview/pages/Utex.tsx

- 리스트 항목의 items-start에서 items-center로 변경하여 정렬 방식 조정
- 스타일링 개선을 통한 불릿포인트와  텍스트 정렬
> ## PR 타입
> ## 변경 사항
- 리스트 항목의 items-start에서 items-center로 변경하여 정렬 방식 조정  
- 스타일링 개선을 통한 불릿 포인트와 텍스트  정렬  
<br/>
> ## 변경 전 문제
불릿포인트와 텍스트가 정렬되지 않았습니다.
<br/>
불릿포인트와 텍스트가 정렬됩니다.
<br/>

refactor: 제품 개요 섹션 리스트 정렬 방식 변경

---

src/layout/Footer/FooterColumn.tsx
src/layout/Footer/index.tsx

> ## PR 타입
> ## 변경 사항
- 기존 리스트 형식에서 드롭다운 UI 형식으로 변경하여 가독성을 개선했습니다.
- 모바일 환경에서 strong 태그에 cursor-pointer를 적용하여 사용자가 클릭 가능하다는 점을 명확하게 전달했습니다.
- isOpen 상태를 활용하여 Footer 데이터의 가시성을 조정했습니다.
- isOpen = false → 메뉴가 접힌 상태로 최소한의 공간만 차지합니다.
- isOpen = true → 사용자가 클릭하면 메뉴가 펼쳐지면서 모든 데이터를 표시합니다.
<br/>
> ## 변경 전 문제
- 기존 리스트 형식이 길어져 스크롤이 증가하고, 가독성이 떨어지는 문제가 있었습니다.
- 모바일 환경에서 항목들이 한 번에 표시되어 UI가 복잡해지는 문제가 있었습니다.
- 클릭 가능한 요소인지 명확하지 않아 UX가 부족했습니다.

:recycle: Refactor - Footer 반응형 디자인 수정

---

src/hooks/useOnClickOutside.ts

> ## PR 타입
> ## 변경 사항
useOnClickOutside 훅을 추가하여 외부 클릭 시 모바일 메뉴가 닫히도록 개선하였습니다.
useOnClickOutside 훅 최적화 및 타입 개선을 하였습니다 
<br/>
> ## 변경 전 문제
이전에는 반응형 네비게이션에서 외부 클릭시 네비게이션이 닫히지 않았습니다.
<br/>
메뉴 외부를 클릭시 자동으로 메뉴가 닫히도록 개선됩니다.
<br/>

feat : 외부 클릭 시 모바일 메뉴 닫히는 훅 생성

---

src/features/profile/pages/History.tsx

> ## PR 타입
> ## 변경 사항
기업 연혁 페이지의 반응형 페이지에서 제목과 텍스트가 왼쪽에 위치하게 변경하였습니다
<br/>
> ## 변경 전 문제
이전에는 의도와 다르게 제목과 텍스트가 중앙 위치하였습니다
<br/>
기업 연혁 페이지의 제목과 텍스트가 올바른 위치에 위치합니다
<br/>

refactor: 기업 연혁 반응형 페이지 제목,텍스트 왼쪽부터 출력되게 변경

---

src/features/home/components/MoreNewsSection.tsx

> ## PR 타입
> ## 변경 사항
- 메인페이지의 모든 소식 보기를 클릭하면 언론보도 페이지로 이동하도록 변경하였습니다.
<br/>
> ## 변경 전 문제
- 이전에는 모든 소식 보기를 클릭하면 언론보도 페이지가 아닌 메인페이지로 다시 이동하였습니다
<br/>
- 모든 소식 보기를 클릭하면 올바른 언론보도 페이지로 이동합니다.
<br/>

refactor: 모든 소식 보기 클릭시 언론 보도 페이지로 이동하도록 변경

---

src/features/profile/pages/ContactUs.tsx

> ## PR 타입
> ## 변경 사항
주소 아이콘의 백그라운드의 크기를 다른 아이콘들과 동일하게 변경하였습니다.
<br/>
> ## 변경 전 문제
이전의 주소 아이콘 백그라운드는 다른 아이콘의 백그라운드와 다르게 가로 길이가 좀 길었습니다
<br/>
다른 아이콘의 백그라운드 크기와 같게 표시됩니다.
<br/>

refactor: 주소 아이콘 백그라운드 크기 다른 아이콘들과 동일하게 변경

---

src/features/business-overview/pages/Overview.tsx

> ## PR 타입
> ## 변경 사항
- px-4 md:px-8 추가하여 반응형에서 좌우 여백 확보
- div추가하여 article 및 리스트 레이아웃 정리
<br/>
> ## 변경 전 문제
이전 사업 소개 모바일 페이지는 섹션의 좌우에 여백이없어 텍스트가 창 끝에 붙어보여서 가시성이 떨어졌습니다.
<br/>
사업 소개 페이지 모바일 화면일때 좌우 여백 추가되어 보기가 편해졌습니다.
<br/>

refactor: 사업 소개 페이지 모바일 좌우 여백 추가 및 레이아웃 정리

---

src/components/Pagination.tsx
src/layout/Footer/index.tsx

> ## PR 타입
> ## 변경 사항
footer 컬럼에 더 넓은 간격 적용 , 페이지네이션 cursor-pointer추가
<br/>
> ## 변경 전 문제
footer 컬럼이 좁았었습니다
페이지네이션에 마우스 오버시 기본값으로 나왔습니다
<br/>
푸터 컬럼 간격이 넓어져 전체 레이아웃의 균형과 가독성이 향상됩니다.
페이지네이션 버튼에 cursor-pointer 효과가 적용되어 마우스 오버 시 사용자에게 인터랙션 가능하다는 시각적 피드백을 제공합니다.
<br/>

refactor: footer 레이아웃 수정 및 페이지네이션 cursor-pointer 추가

---

src/features/news/components/NewsCardList.tsx

> ## PR 타입
> ### 변경 내용1
이미지 랩 요소에 p-2와 mt-4 클래스를 추가하여 이미지와 주변 요소 간의 적절한 간격을 확보하였습니다
<br/>
> ### 변경 내용2
horizontal및 vertical  레이아웃 컴포넌트에 p-4 클래스를 적용하여 내부 여백을 추가하였습니다
<br/>
레이아웃 컴포넌트들의 여백이 부족해 콘텐츠가 화면에 너무 붙어 표시되어 가독성과 시각적 구분 좋지 않았습니다
<br/>
각 요소에 적절한 여백을 추가함으로써 가독성이 상승됩니다
모바일
아이패드 프로
아이패드 에어

refactor: 뉴스페이지 모바일 화면의 좌우 여백 수정

---

src/layout/Navbar/NavbarDesktop.tsx
src/layout/Navbar/NavbarMobile.tsx

> ## PR 타입
> ### 변경 내용1
Navbar 데스크탑 브레이크포인트 변경 md 에서 lg로 변경 및 로고 위치 조정하였습니다
<br/>
> ### 변경 내용2
refactor: 모바일 메뉴 브레이크포인트 변경 md에서lg 변경하였습니다
<br/>
> ### 변경 전 문제
아이패드 미니,에어 해상도에서 네비게이션의 메인메뉴,서브메뉴가 수직정렬이 되어 있지 않았습니다
<br/>
> ### 변경 후 기대 효과
아이패드 미니,에어 등 특정 해상도에서도 모바일처럼 햄버거 메뉴가 표시됩니다.
이제 로고가 왼쪽 창에 붙지 않습니다

refactor 메인페이지 반응형웹 테블릿 크기일시 모바일처럼 햄버거 메뉴 나오게 수정 및 로고 위치 조정

---

src/features/home/index.tsx

- sectionRef 컨테이너에 overflow-x-hidden 클래스를 추가 sectionRef 컨테이너에 가로 스크롤 숨김 적용
> ## PR 타입
> ### 변경 내용1
sectionRef 컨테이너에 overflow-x-hidden 클래스를 추가 sectionRef 컨테이너에 가로 스크롤 숨김 적용하여 여백을 제거 하였습니다.
<br/>
> ### 변경 전 문제
이전에는 메인페이지에 모바일 화면에 가로 여백이 생겨 스크롤이 되었습니다.
<br/>
모바일 화면에 여백이 제거되어 가로 스크롤이 제거됩니다.

-refactor  메인페이지 모바일 화면 가로 스크롤 숨김 적용

---

package-lock.json
package.json
src/components/Carousel.tsx
src/components/SectionTitle.tsx
src/features/news/components/NewsCardList.tsx
src/features/news/pages/News.tsx

- swiper 설치
- PC, 모바일 (z 플립5) 반응형 및 컴포넌트 작업 (CL: 453)
> ## PR 타입
> ### 의존성 설치
> swiper , @types/swiper 의존성이 추가되었습니다.
<br/>
> ### 캐러셀 슬라이드 컴포넌트 생성
- 캐러셀 슬라이드 컴포넌트(Carousel.tsx)가 추가되었습니다.
- 캐러셀 슬라이드는 현재 뉴스 페이지에 적용되어있으며 유틸리티하게 리팩토링 작업이 필요합니다.
- 현재 PC, Mobile 일부 기기 (Z fold5)에 최적화 되어있습니다.

:sparkle: feat - 캐러셀 슬라이드 생성 및 적용

---

src/features/profile/pages/ContactUs.tsx

> ## PR 타입
> ### 반응형 적용
> - SectionLayout에 px-4 sm:px-6 md:px-8 lg:px-10 xl:px-12처럼 다양한 뷰포트 사이즈별로 좌우 여백을 설정
> 
<br/>
> ### 반응형 적용
>
> - 그리드 구조 재설정기본 1열에서 시작해 태블릿 환경에서는 2열, 데스크톱 환경에서는 5열을 사용
> ### 리스트와 지도 사이 여백 적용
>
> - gap-8 md:gap-12를 적용해 카드 목록과 지도 사이의 여백 적용
> ### 지도 크기 조정
>
> - 지도영역에 h-64와 md:h-full을 사용해 모바일~데스크톱에서 균형 잡힌 크기 유지
<br/>
<br/>
> ### 변경 후 기대 효과
>
> (변경 후 기대되는 결과를 작성하세요.)
https://github.com/orgs/TitovCompany/projects/2/views/1?pane=issue&itemId=98676408&issue=TitovCompany%7CVisionlife_FE%7C141
https://github.com/orgs/TitovCompany/projects/2/views/1?pane=issue&itemId=98679514&issue=TitovCompany%7CVisionlife_FE%7C144
> ### 테스트 디바이스
> (iPadmini),(iPadair),(iPadPro),(Z Fold 2,3,4,5),(Z Flip 3,4,5)(iPhone16,Plus,ProMax)

refactor: ContactUs 컴포넌트 레이아웃 및 반응형 스타일링 개선

---

src/components/Dropdown.tsx
src/features/profile/index.tsx
src/features/profile/pages/ContactUs.tsx
src/hooks/useToggle.ts
src/layout/Footer/FooterColumn.tsx

> ## PR 타입
> ### 드롭다운 메뉴 컴포넌트 생성
- 작은 화면에서는 가독성을 높이기 위해 TabNavbar 대신 드롭다운 메뉴를 사용
- 반응형 디자인을 고려하여 md 이상에서는 기존 TabNavbar 유지 (CL: 472)
> ### useToggle 커스텀 훅 생성
- isOpen 상태를 공통으로 관리하기 위해 useToggle 훅을 생성
- isOpen, toggle(), close() 등의 메서드를 제공하여 재사용성을 높임
- Dropdown에서 메뉴 클릭 시 자동으로 닫히도록 적용하여 UX 개선

♻️ refactor: 모바일 환경에서 TabNavbar 대신 드롭다운 메뉴 적용

---

src/features/profile/pages/History.tsx

> ## PR 타입
> ### History 컴포넌트 레이아웃 변경
기존 History 컴포넌트를 리스트 형태에서 좌우 교차 타임라인 레이아웃으로 리팩토링하였습니다.
<br/>

refactor: History 컴포넌트 좌우 교차 타임라인 레이아웃으로 변경

---

src/features/history/index.tsx

> ## PR 타입
> ### 레이아웃 개선
모든 히스토리 카드를 우측 정렬로 통일하였고 년도 는 dot 기준 왼쪽으로 가도록 레이아웃을 수정하였습니다.
<br/>

refactor: 히스토리 타임라인 카드 정렬 수정

---

src/features/history/Card.tsx
src/features/history/Dot.tsx
src/features/history/HistoryTimeline.tsx
src/features/history/Year.tsx
src/features/history/index.tsx
src/layout/PageLayout.tsx

> ## PR 타입
> ### 모바일 환경 메뉴와 히어로 섹션의 간격 제거
>
> 'lg:pt-[calc(102px)]', 
lg 이상에서만 패딩으로 변경하여 모바일에서의 간격이 제거되었습니다.
<br/>
> ### 타임라인 페이지 반응형 레이아웃 조정
데스크탑 연도 선 카드 구조 
테스트 기기 UDEA Monitor 
테블릿  연도 카드 구조
테스트 기기 iPad Pro,iPad mini,iPad Air
모바일 년도 카드 세로 구조  모바일에서는 년도를 가로로 한 줄로 표시하도록 변경
테스트 기기 iPhone 12Pro,iPhone 14Pro Max,iPhone SE
> ###  연도,점,카드 부분 별도 컴포넌트로 분리
기존의 index.tsx에 있던 연도,점,카드 컴포넌트를 따로 분리하였습니다. [b7d5f58]

refactor: 모바일 화면에서 히어로 섹션과 메뉴의 세로 간격이 없게 수정,타임라인 반응형 레이아웃 조정 

---

src/features/home/index.tsx

> ## PR 타입
> ### 메인페이지의 반응형 레이아웃 조정
>테스트 기기 IPhone se,IPhone 14 Pro Max
Company 세로로 정렬(수정전)
</br>
Company 세로로 정렬(수정후)
</br>
</br>
WhyUsSection 세로로 정렬
</br>
Global Business 모바일에서는 텍스트 중앙정렬 대신 왼쪽정렬하게 변경 하였습니다
</br>
News 뉴스는 세로로 쌓이는 구조로 변경하고 이미지 타이틀을 flex row 정렬로 변경하였습니다

refactor:  메인페이지 반응형 레이아웃 조정
